<a href="https://colab.research.google.com/github/lehuutrung1412/Learning_Machine_Learning/blob/main/Singular_Value_Decomposition_Principal_Component_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Đồ án CS115


##Singular Value Decomposition 

In Linear Algebra, we learnt about diagonalization : a square matrix $A \in R^{n\times n}$ is diagonalizable if exist a invertible matrix $P$ and a diagonal matrix $D$ so that:
 $$ \mathbf{A} = \mathbf{P} \mathbf{D} \mathbf{P}^{-1} $$
But it only happens in square matrix, not all kind of matrix. So **Singular Value Decomposition** (SVD) is a ***special matrix factorization*** method for *any* real matrix, which helps us a lot in working with matrix and big data: storing matrix, finding features in data reduction,dimesionality reduction, etc. It's considered as a foundation of Machine Learning, one of the most useful tool in numerical linear algebra numerical for data processing. It's also the basis of Principal Component Analysis(PCA) - a widely techniques for analysis high dimesional data. SVD is a basis of facial regcontion algorithm.


#### Introduction to SVD


The singular value decomposition of a matrix is usually referred to as the SVD.

This is the final and best factorization of any matrix:

$$\mathbf{A}_{m \times n} = \mathbf{U}_{m \times m}\mathbf{\Sigma}_{m \times n} (\mathbf{V}_{n \times n})^T  ~~~~~(1)$$

where $U$ is **orthonormal**,  $\Sigma$ is almost a **diagonal** matrix - only contains real numbers ordered *descending* $\sigma_{1,2,....m}$ in main **diagonal** line ,$V$ is also **orthonormal**

<br/>
<br/>

The image below describes the SVD for matrix A in 2 cases: $m < n $ and $m > n$   

<img src="https://machinelearningcoban.com/assets/26_svd/svd.png" width="75%" height="75%"/>

####Caculating SVD

Ignoring dimesion of the matrix, base on equation $(1)$ we can compute $AA^T$ like this:

\begin{eqnarray}
\mathbf{AA}^T &=& \mathbf{U}\mathbf{\Sigma} \mathbf{V}^T (\mathbf{U}\mathbf{\Sigma} \mathbf{V}^T)^T \ 
&=& \mathbf{U}\mathbf{\Sigma} \mathbf{V}^T \mathbf{V}\mathbf{\Sigma}^T\mathbf{U}^T \ 
&=& \mathbf{U}\mathbf{\Sigma}\mathbf{\Sigma}^T\mathbf{U}^T = \mathbf{U}\mathbf{\Sigma}\mathbf{\Sigma}^T\mathbf{U}^{-1}  ~~~~~ (2)
\end{eqnarray}


$\Sigma \Sigma^T$ is a diagonal matrix contains $\sigma^2_{1},\sigma^2_{2}...\sigma^2_{m}$. These $\sigma^2$ is egien values of $AA^T$. Cause $AA^T$ is a positive semi-definite matrix so its eigen values is not negative. Those $\sigma_j$ is square root of $AA^T$ eigen values - also called as *singular values*. Column vectors of $U$ are eigen vectors of $AA^T$. We call these vectors are *left-singular vectors*.

</br> 

In the otherhand, caculating $A^TA$ will look like this:
\begin{eqnarray}
\mathbf{AA}^T &=& (\mathbf{U}\mathbf{\Sigma} \mathbf{V}^T)^T \mathbf{U}\mathbf{\Sigma} \mathbf{V}^T \ 
&=& \mathbf{V}\mathbf{\Sigma}^T\mathbf{U}^T   \mathbf{U}\mathbf{\Sigma} \mathbf{V}^T \
&=& \mathbf{V}\mathbf{\Sigma}^T\mathbf{\Sigma}\mathbf{V}^T =  \mathbf{V}\mathbf{\Sigma}^T\mathbf{\Sigma}\mathbf{V}^{-1} ~~~~~ (3)
\end{eqnarray}

Similar to $AA^T$, column vectors of $V$ are eigen vectors of $A^TA$. We call these vectors are *right-singular vectors*.

</br>

From $(2)(3)$, we can get matrix $\Sigma, U , V$ just by diagonalizing $A^TA$ or $AA^T$.


In [ ]:
import numpy as np
from numpy import linalg

m, n = 3, 5 #m.n dim
A = np.random.randint(0,50,(m, n)) #random A matrix
print(A)
#caculating the SVD of A
U, S, V = linalg.svd(A)

#creating matrix S cause  linalg.svd just return Sigma as an array
Smatrix = np.zeros((m,n))
for i in range(np.linalg.matrix_rank(A)):
    Smatrix[i,i] += S[i]

print(U)
print()
print(Smatrix)
print()
print(V)




[[24 39 38 20 13]
 [21 42  6 18 27]
 [24 24 39 18 32]]
[[-0.61278965  0.25956921 -0.74639981]
 [-0.51434354 -0.84807673  0.12734433]
 [-0.59994964  0.4619412   0.65320039]]

[[101.91680844   0.           0.           0.           0.        ]
 [  0.          27.43858371   0.           0.           0.        ]
 [  0.           0.          16.8845575    0.           0.        ]]

[[-0.39156404 -0.58773442 -0.48834049 -0.3170534  -0.40279842]
 [-0.01798057 -0.52515227  0.83061418 -0.06410882 -0.17280606]
 [ 0.025908   -0.4787997  -0.12581386 -0.0520115   0.86691712]
 [-0.27306035 -0.21073582 -0.08043719  0.93299068 -0.0639273 ]
 [-0.87813502  0.32422925  0.2220459  -0.1489644   0.22860337]]


But in practice, we dont compute both equation $(2)(3)$. We choose 1 equation, compute $U$ or $V$ and $\Sigma$, then using the definition of SVD $(1)$ to compute the leftover.
Example:

$$A = \begin{pmatrix} 5 & 5 \\ -1 & 7 \end{pmatrix} $$

We're using equation $(3)$
$$ A^TA = \begin{pmatrix} 5 & -1 \\ 5 & 7 \end{pmatrix} \begin{pmatrix} 5 & 5 \\ -1 & 7 \end{pmatrix} = \begin{pmatrix} 26 & 18 \\ 18 & 74 \end{pmatrix} $$
Diagonalizing $A^TA$, we got $\Sigma, V$.
$$det(A^TA - \lambda I ) = 0$$
$$ \lambda^2 - 100\lambda + 1600 = 0$$
$$ (\lambda - 20 )(\lambda-80) = 0$$
$$=> \lambda = 80,20$$
$with \, \lambda_1 = 80 $
$$A^TA - 80I = \begin{pmatrix} -54 & 18 \\ 18 & -6 \end{pmatrix}$$
$$ => v_1 = \begin{pmatrix} 1\\ 3 \end{pmatrix} $$

$with \, \lambda_2 = 20 $
$$A^TA - 20I = \begin{pmatrix} 6 & 18 \\ 18 & 54 \end{pmatrix}$$
$$ => v_2 = \begin{pmatrix} -3 \\ 1 \end{pmatrix}  $$
But $v1,v2$ is orthogonal already. Normalizing $v_1, v_2$ .So now, we got:

$$ \Sigma = \begin{pmatrix} 4\sqrt{5}& 0 \\ 0 & 2\sqrt{5} \end{pmatrix} ,
V = \begin{pmatrix} 1/\sqrt{10} & -3/\sqrt{10} \\ 3/\sqrt{10} & 1/\sqrt{10} \end{pmatrix} $$

Now we use the SVD defination:

$$ A = U \Sigma V^T $$
$$ AV = U \Sigma $$

$$ AV = \begin{pmatrix} 5 & 5 \\ -1 & 7 \end{pmatrix} 
\begin{pmatrix} 1/\sqrt{10} & -3/\sqrt{10} \\ 3/\sqrt{10} & 1/\sqrt{10} \end{pmatrix} =  \begin{pmatrix} 2\sqrt{10} & -\sqrt{10} \\ 2\sqrt{10} & \sqrt{10} \end{pmatrix} = U \Sigma$$

$$=> U = AV\Sigma^{-1}=  \begin{pmatrix} 2\sqrt{10} & -\sqrt{10} \\ 2\sqrt{10} & \sqrt{10} \end{pmatrix}
 \begin{pmatrix} \sqrt{5}/20 & 0 \\ 0 & \sqrt{5}/10 \end{pmatrix} =
 \begin{pmatrix} 1/\sqrt{2} & -1/\sqrt{2} \\ 1/\sqrt{2} & 1/\sqrt{2} \end{pmatrix}
  $$

Conclusion, we got 3 matrix $U, \Sigma, V$ as a result after SVD-factorization matrix $A$
$$A = \begin{pmatrix} 5 & 5 \\ -1 & 7 \end{pmatrix} = U\Sigma V^T $$

$$U = \begin{pmatrix} 1/\sqrt{2} & -1/\sqrt{2} \\ 1/\sqrt{2} & 1/\sqrt{2} \end{pmatrix}
, \Sigma = \begin{pmatrix} 1/\sqrt{10} & -3/\sqrt{10} \\ 3/\sqrt{10} & 1/\sqrt{10} \end{pmatrix}
, V =\begin{pmatrix} 1/\sqrt{10} & -3/\sqrt{10} \\ 3/\sqrt{10} & 1/\sqrt{10} \end{pmatrix} 
$$

####Some special SVD

In reality, data is very complex, its can be lots of entries and features. For example, human genetic data can be a sequence of thousand features and there are thousand of people - which is huge; finding "eigen face" of people for facial regconition, a gray picture contains 1 face, may have a size 400 x 400 pixel, having different lighting condition, enormous data like that can't be interpreted and analysed. Even though, after doing SVD with these data, its still large. Truncated SVD will help us solve this big data problem. We will store a part of the origin SVD, but still knowing the main features.

###### *Compacted SVD*

Equation $(1)$ can be written as below:
  $$ \mathbf{A} = \sigma_1 \mathbf{u}_1 \mathbf{v}^T_1 + \sigma_2\mathbf{u}_2\mathbf{v}_2^T + \dots + \sigma_r\mathbf{u}_r\mathbf{v}_r^T $$
with every $u_i v_i^T, 1 \leq i \leq r$ is a rank-1 matrix.

In this formula, $A$ only depends on *first r columns* of $U,V$ and *r* non-values in main diagonal line of $\Sigma$. So we have a better decomposition called ***compacted SVD***: 
$$ \mathbf{A} = {\mathbf{U}}_r{\Sigma}_r({\mathbf{V}}_r)^T $$
If our $A$ has a smaller rank than *columns and rows* of $A$, meaning $ r \ll m,n$, we have benefit of compacted SVD in storing data.


<img src="https://machinelearningcoban.com/assets/26_svd/svd_truncated.png" width="75%" height="50%"/>



###### *Truncated SVD*
Remembered, $\sigma$ values in the main diagonal line of $\Sigma$ is non-zero and ordered descending. In common, some first values of $\sigma_i$ are large, remaining values are small and can be zero. We dont want to store all the values in the SVD. Then, we can approximate matrix  $A \approx \hat{A} $ equal to sum of $k < r$ rank 1 matrices

$$\mathbf{A} \approx \mathbf{\hat{A} } = U_k \Sigma_k V_k^T = \sigma_1 \mathbf{u}_1 \mathbf{v}^T_1 + \sigma_2\mathbf{u}_2\mathbf{v}_2^T + \dots + \sigma_k\mathbf{u}_k\mathbf{v}_k^T $$

Pushing away $r-k$ small and non-zero values in *SVD* is called ___Truncated SVD___. The error of subtraction $A-A_k$ is caculated by the Frobineous norm of the subtraction.But we have a theorem for it. *The error will equal to total square of the cut-off eigen values in truncated SVD*.

$$ ||\mathbf{A} - \mathbf{A}_k||_F^2 = \sum_{i = k + 1}^r \sigma_i^2 ~~~ (4)$$
Proof: 
\begin{eqnarray}
    ||\mathbf{A} - \mathbf{A}_k||_F^2 & = & ||\sum_{i = k + 1}^r \sigma_i \mathbf{u}_i\mathbf{v}_i^T ||_F^2    & (5)\ \\
    & = & \text{trace}\left\{ \left(\sum_{i = k + 1}^r \sigma_i \mathbf{u}_i\mathbf{v}_i^T\right)
    \left(\sum_{j = k + 1}^r \sigma_j \mathbf{u}_j\mathbf{v}_j^T\right)^T
    \right\} & (6) \ \\
    &=& \text{trace}\left\{ \sum_{i = k + 1}^r \sum_{j = k + 1}^r \sigma_i\sigma_j \mathbf{u}_i\mathbf{v}_i^T \mathbf{v}_j \mathbf{u}_j^T
    \right\} & (7) \  \\
    &=& \text{trace}\left\{ \sum_{i = k + 1}^r  \sigma_i^2\mathbf{u}_i\mathbf{u}_i^T
    \right\} & (8) \  \\
    &=& \text{trace}\left\{ \sum_{i = k + 1}^r  \sigma_i^2\mathbf{u}_i^T\mathbf{u}_i
    \right\} & (9) \  \\
    &=& \text{trace}\left\{ \sum_{i = k + 1}^r  \sigma_i^2
    \right\} & (10) \  \\
    & = & \sum_{i = k + 1}^r \sigma_i^2 & 
\end{eqnarray}

With $k=0$, we got: 
$$ ||\mathbf{A}||_F^2 = \sum_{i = 1}^r \sigma_i^2~~~~ (11) $$
Fron $(4)(11)$ we can infer:
$$ \frac{||\mathbf{A} - \mathbf{A}_k||_F^2}{||\mathbf{A}||_F^2} = {\frac{\sum_{i = k + 1}^r \sigma_i^2}{\sum_{j = 1}^r \sigma_j^2}} ~~~~ (12)
$$
Thus, *the errorr of this approximation is very small if the cut-off eigen values is negligible for comparing to first k eigen values*. The theorem $(4)$ is important for caculating how much information we want to store. From equation $(12)$, we can pick smallest $k$ for storing up to $y \% $ information. We can call it a low-rank approximation.




###### *Best k-rank approximation*

This course : <a href="https://www.cs.princeton.edu/courses/archive/spring12/cos598C/svdchapter.pdf">SVD - Princeton Course</a> proving that $A_k$ is also a root in this optimization problem: 
\begin{eqnarray}
\min_{\mathbf{B}} &&||\mathbf{A} - \mathbf{B}||_F \ ~~~~~~
\text{s.t.} ~~ \text{rank}(\mathbf{B}) = k ~~~~~~~~~~~~~~ ()
\end{eqnarray}

In above proof, $||\mathbf{A} - \mathbf{A}_k||_F^2 = \sum_{i = k + 1}^r \sigma_i^2 ~~~~ (4)$. If we using 2-norm instead of Frobeneous norm (F-norm) to caculate the error, $A_k$ is also a root for it.

\begin{eqnarray}
\min_{\mathbf{B}} &&||\mathbf{A} - \mathbf{B}||_2 \ 
\text{s.t.} && \text{rank}(\mathbf{B}) = k ~~~~~~~~~~~~~~ ()
\end{eqnarray}


####Application of SVD


Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam et tellus tempor est facilisis tempus quis id dolor. Donec varius pharetra velit vel euismod. Sed et vehicula orci.



##Principal Component Analysis (PCA)

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam et tellus tempor est facilisis tempus quis id dolor. Donec varius pharetra velit vel euismod. Sed et vehicula orci.


####Some Linear Algebra for PCA


Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam et tellus tempor est facilisis tempus quis id dolor. Donec varius pharetra velit vel euismod. Sed et vehicula orci.



####Into PCA

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam et tellus tempor est facilisis tempus quis id dolor. Donec varius pharetra velit vel euismod. Sed et vehicula orci.



####PCA Caculating steps

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam et tellus tempor est facilisis tempus quis id dolor. Donec varius pharetra velit vel euismod. Sed et vehicula orci.



####Relation between PCA and SVD

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam et tellus tempor est facilisis tempus quis id dolor. Donec varius pharetra velit vel euismod. Sed et vehicula orci.



####Application and Example of PCA

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam et tellus tempor est facilisis tempus quis id dolor. Donec varius pharetra velit vel euismod. Sed et vehicula orci.
